### ISSUE TITLE
Received FAILURE signal with UniqueId

### ISSUE THREAD

**Issue by nicklester** [cfn-modules/ec2-instance-amazon-linux#23]
Hi,

Cannot create EC2 instance - getting the above error. Have attached system log, as well as section of template.

[syslog.txt](https://github.com/cfn-modules/ec2-instance-amazon-linux/files/6435809/syslog.txt)

[template.txt](https://github.com/cfn-modules/ec2-instance-amazon-linux/files/6435822/template.txt)
<img width="560" alt="Screenshot 2021-05-06 at 16 31 49" src="https://user-images.githubusercontent.com/1490089/117325777-f25e8c80-ae88-11eb-9db3-9030ba224acc.png">

**Comment by nicklester** [comment]
Seems to be linked to the efs module. Once I removed this from the instance the stack created successfully ...

**Comment by michaelwittig** [comment]
I believe you need to add an `ClientSgModule1: !GetAtt 'ClientSg.Outputs.StackName'` that points to the same ClitnSG that you use to create the efs-file-system.

see https://github.com/cfn-modules/ec2-instance-amazon-linux/blob/master/test/file-system.yml

**Comment by nicklester** [comment]
Hi @michaelwittig - understood. That worked correctly. 
Many thanks
